
##################################################
# Filter transcripts by the following conditions #
##################################################

type_of_study : []
#<options> ['RT_qPCR', 'gene_silence', 'genetic_transformation', 'genomics', 'knock_out', 'proteomics', 'transcriptomics']

MANIPULATED_GENE : 2
#<options> 2, 1, 0 
#2 = include all
#1 = include only studies that manipulated genes
#0 = include only studies that did not manipulat genes

pathway  : []

MIN_NUM_SAMPLED : 1 #minimum number of studies that sampled gene X

MIN_NUM_MANIPULATED : 0 #minimum number of studies that manipulated gene X

MIN_NUM_DETECTED : 1 #minimum number of studies that detected gene X as a candidate gene

###########################
# Boostrapping parameters #
###########################

RSAMPLE_SIZE : 100 #number of genes to randomly sample

SAMPLE_N : 10 #number of boostrap w/ replacement samples